
nebhefqshqndvplyzjwv

[functions]
[functions.create-subscription]
verify_jwt = true
[functions.check-subscription]
verify_jwt = true
[functions.schedule-payment]
verify_jwt = true
[functions.plaid-link]
verify_jwt = true

