
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nebhefqshqndvplyzjwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lYmhlZnFzaHFuZHZwbHl6and2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NDM4MTksImV4cCI6MjA2MjMxOTgxOX0.WMmShpVxgkXt0CdmVvgSCyMqRNz8WGCFUTsK_lnkPrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
